language: node_js

node_js:
 - "node"

before_install:
 - npm install -g codecov
 - sed "s/API_KEY=/API_KEY=${POTTER_API_KEY}/" .env.sample > .env

script:
  - npm run lint
  - npm run test

after_success:
  - codecov --disable=gcov