language: node_js

node_js:
 - "node"

before_install:
 - npm install -g codecov
 - sed 's/API_KEY=/API_KEY=7192a8dc-e1d8-4aa2-b2a0-47f08904077c/' .env.sample > .env

script:
  - npm run lint
  - npm run test

after_success:
  - codecov --disable=gcov